### ISSUE TITLE
Does not have setup function

### ISSUE THREAD

**Issue by batman202012** [Cog-Creators/Cog-Cookiecutter#2]
When using cookie cutter and trying to load the cog it claims the cog does not have a setup function

```
Dec 27 01:16:00 localhost bash[1121]:   File "/usr/local/lib/python3.8/dist-packages/redbot/core/bot.py", line 1205, in load_extension
Dec 27 01:16:00 localhost bash[1121]:     raise discord.ClientException(f"extension {name} does not have a setup function")
Dec 27 01:16:00 localhost bash[1121]: discord.errors.ClientException: extension Minecraft does not have a setup function
Dec 27 01:40:24 localhost bash[1121]: [2020-12-27 01:40:24] [ERROR] red: Package loading failed
Dec 27 01:40:24 localhost bash[1121]: Traceback (most recent call last):
Dec 27 01:40:24 localhost bash[1121]:   File "/usr/local/lib/python3.8/dist-packages/redbot/core/core_commands.py", line 171, in _load
Dec 27 01:40:24 localhost bash[1121]:     await bot.load_extension(spec)
Dec 27 01:40:24 localhost bash[1121]:   File "/usr/local/lib/python3.8/dist-packages/redbot/core/bot.py", line 1205, in load_extension
Dec 27 01:40:24 localhost bash[1121]:     raise discord.ClientException(f"extension {name} does not have a setup function")
Dec 27 01:40:24 localhost bash[1121]: discord.errors.ClientException: extension Minecraft does not have a setup function
```

If you require more info from the logs I can get the error to occur once more. Just hard to get log data from systemd, she is a fickle mistress.

**Comment by Jackenmen** [comment]
Setup function does exist in the cookie cutter template so you most likely just added a wrong path. See the folder layout in our docs for more information:
https://docs.discord.red/en/stable/guide_cog_creation.html#testing-your-cog

**Comment by batman202012** [comment]
I checked the path, the cog appears in the cog list but upon load ([p]load Minecraft) it throws out that error ^. Just to make sure the path would be to the folder containing the all the cog files (__init__.py, Minecraft.py, info.json, and __pycache__). I also made sure that all the files in the folder had execution permissions. Also I appreciate such a fast reply +rep.

**Comment by Jackenmen** [comment]
> Just to make sure the path would be to the folder containing the all the cog files

@batman202012 That is incorrect. You're supposed to add the folder **containing** the folder you're talking about. If you read the part of docs talking about the folder layout again, more carefully, you should see what I mean.

**Comment by batman202012** [comment]
And it works. The devil is in the details. Thanks for your help and sorry for wasting your time with such a dumb question. Hopefully if anyone else has any issues this should help.

**Comment by Jackenmen** [comment]
@batman202012 one more thing. Next time you have some coding-related question like this, I would suggest asking in #coding channel on our support server: https://discord.gg/red
